"""Rebuild SOURCES.md from the frontmatter of notes/x/*.md.

Run from the repo root:
    python docs/techniques/team2/tools/build_sources_index.py

Each note starts with a YAML-ish frontmatter block (source, posted, kind, ...). The row's
title is the first Markdown H1 if present, else the first non-empty body line. Dates for
X status ids are cross-checked against the id's snowflake timestamp (the Thread Reader
header omits the year for recent posts).
"""
from __future__ import annotations

import datetime as dt
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent.parent
NOTES = HERE / "notes" / "x"
OUT = HERE / "SOURCES.md"
TWITTER_EPOCH_MS = 1288834974657


def snowflake_date(status_id: str) -> str:
    ms = (int(status_id) >> 22) + TWITTER_EPOCH_MS
    return dt.datetime.fromtimestamp(ms / 1000, dt.timezone.utc).strftime("%Y-%m-%d")


def parse(path: pathlib.Path) -> dict:
    text = path.read_text(encoding="utf-8")
    fm: dict[str, str] = {}
    body = text
    if text.startswith("---"):
        end = text.find("\n---", 3)
        for line in text[3:end].splitlines():
            if ":" in line and not line.startswith(" "):
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip()
        body = text[end + 4:]
    title = ""
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("# "):
            title = s[2:]
            break
    if not title:
        for line in body.splitlines():
            s = line.strip()
            if s:
                title = s
                break
    m = re.search(r"status/(\d+)", fm.get("source", ""))
    sid = m.group(1) if m else ""
    posted = fm.get("posted", "")[:10]
    if sid and re.fullmatch(r"\d{4}-\d{2}-\d{2}", posted):
        sf = snowflake_date(sid)
        if sf[:7] != posted[:7]:
            posted = f"{sf} (frontmatter said {posted})"
    elif sid and not posted:
        posted = snowflake_date(sid)
    return {"file": path.name, "posted": posted or fm.get("posted", "?"), "id": sid,
            "kind": fm.get("kind", ""), "title": title.replace("|", "/")[:110],
            "url": fm.get("source", "")}


def main() -> None:
    rows = [parse(p) for p in sorted(NOTES.glob("*.md")) if not p.name.startswith("PARTIAL")]
    rows.sort(key=lambda r: r["posted"])
    lines = ["# Sources — everything captured from @Team2Trading (verbatim under `notes/x/`)", "",
             f"*Generated by `tools/build_sources_index.py` on {dt.date.today().isoformat()}; "
             f"{len(rows)} notes. Re-run after adding a note. Ids not yet captured are listed in "
             "`notes/x/PARTIAL-threads-seen-not-yet-captured.md`.*", "",
             "| Posted | Kind | Title / first line | Note |", "|---|---|---|---|"]
    for r in rows:
        link = f"[{r['id'] or 'post'}]({r['url']})" if r["url"] else ""
        lines.append(f"| {r['posted']} | {r['kind']} | {r['title']} {link} | `{r['file']}` |")
    vids = sorted((HERE / "notes" / "video").glob("*.md"))
    if vids:
        lines += ["", "## Video transcripts (`notes/video/`)", "",
                  "| Uploaded | Title | Minutes | Note |", "|---|---|---|---|"]
        for v in vids:
            raw = v.read_text(encoding="utf-8")
            title = re.search(r"^title: (.*)$", raw, re.M)
            up = re.search(r"^uploaded: (.*)$", raw, re.M)
            mins = re.search(r"^duration_min: (.*)$", raw, re.M)
            lines.append(f"| {up.group(1) if up else '?'} | {title.group(1) if title else v.stem} | "
                         f"{mins.group(1) if mins else '?'} | `{v.name}` |")
    imgs = sorted((HERE / "notes" / "x" / "images").glob("*.jpg"))
    lines += ["", f"## Images: {len(imgs)} files under `notes/x/images/` — "
                  "descriptions of the ones read are in `notes/x/images/INDEX.md`"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} rows, {len(vids)} videos, {len(imgs)} images)")


if __name__ == "__main__":
    main()
